name: Update profile
on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}]

jobs:
  metrics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          committer_message: Update metrics
          base: activity, community, repositories, metadata
          base_indepth: true
          plugin_lines: true
          plugin_traffic: true
          plugin_languages: true
          plugin_languages_indepth: true

      - name: Generate achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: other.svg
          committer_message: Update other
          config_padding: 0
          base: ""
          plugin_achievements: true
          plugin_achievements_ignored: gister, follower, inspirer
          plugin_achievements_limit: 14

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Generate snek
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake.svg?palette=github-dark
      - name: Commit snek
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add snake.svg
          git commit -m "Update snek"
      - name: Push snek
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SNAKE_TOKEN }}
          branch: ${{ github.ref }}
